# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    cd Khana\ POC
  displayName: 'Change to correct directory'
  
- script: |
    npm install
  displayName: 'npm install'

- script: |
    npx truffle compile
    npx truffle test
  displayName: 'truffle compile & test'
